"""Step 9: export filter, normalizer and a linear classifier to a C header for the MCU firmware."""

import argparse
import datetime

import joblib
import numpy as np

from pipeline import config
from pipeline.step2_filtering.filters import design_filters
from pipeline.step5_normalization.normalizer import MinMaxNormalizer


def c_float(v):
    s = "{:.9g}".format(float(v))
    if not any(ch in s for ch in ".e"):
        s += ".0"
    return s + "f"


def c_array_1d(values):
    return "{" + ", ".join(c_float(v) for v in values) + "}"


def c_array_2d(rows, indent="    "):
    return "{\n" + ",\n".join(indent + c_array_1d(r) for r in rows) + "\n}"


def build_header(sos, normalizer, weights, bias, zc_threshold, model_name):
    n_features = len(normalizer.feature_min)
    names = ", ".join('"{}"'.format(g) for g in config.GESTURES)
    return """/* Auto-generated by pipeline/step9_deployment/export_c.py on {date}. Do not edit. */
#ifndef EMG_MODEL_H
#define EMG_MODEL_H

#define EMG_FS_HZ             {fs}
#define EMG_NUM_CHANNELS      {nch}
#define EMG_WINDOW_SIZE       {win}
#define EMG_WINDOW_STEP       {step}
#define EMG_TRANSIENT_SAMPLES {transient}
#define EMG_NUM_SOS           {nsos}
#define EMG_NUM_FEATURES      {nfeat}
#define EMG_NUM_CLASSES       {ncls}

/* 1 Hz EMA baseline tracker: b += alpha * (x - b) */
static const float EMG_BASELINE_ALPHA = {alpha};

/* 50 Hz notch + Butterworth {band_lo:g}-{band_hi:g} Hz bandpass; rows = b0 b1 b2 a0 a1 a2 (a0 = 1) */
static const float EMG_SOS[EMG_NUM_SOS][6] = {sos};

static const float EMG_ZC_THRESHOLD = {zc};

/* Feature order: {feat_names} */
static const float EMG_FEAT_MIN[EMG_NUM_FEATURES] = {fmin};
static const float EMG_FEAT_MAX[EMG_NUM_FEATURES] = {fmax};

/* Linear classifier ({model}): score_k = b_k + sum_j W[k][j] * z_j, label = argmax_k */
static const float EMG_W[EMG_NUM_CLASSES][EMG_NUM_FEATURES] = {w};
static const float EMG_B[EMG_NUM_CLASSES] = {b};

static const char *const EMG_CLASS_NAMES[EMG_NUM_CLASSES] = {{{names}}};

#endif /* EMG_MODEL_H */
""".format(
        date=datetime.date.today().isoformat(),
        fs=config.FS,
        nch=config.N_CHANNELS,
        win=config.WINDOW_SIZE,
        step=config.WINDOW_STEP,
        transient=config.TRANSIENT_SAMPLES,
        nsos=len(sos),
        nfeat=n_features,
        ncls=len(config.GESTURES),
        alpha=c_float(config.BASELINE_ALPHA),
        band_lo=config.BANDPASS[0],
        band_hi=config.BANDPASS[1],
        sos=c_array_2d(sos),
        zc=c_float(zc_threshold),
        feat_names=", ".join(config.FEATURE_NAMES),
        fmin=c_array_1d(normalizer.feature_min),
        fmax=c_array_1d(normalizer.feature_max),
        model=model_name,
        w=c_array_2d(weights),
        b=c_array_1d(bias),
        names=names,
    )


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", default="lda", help="a linear model saved by Step 7 (must expose coef_ / intercept_)")
    parser.add_argument("--out", default=str(config.FIRMWARE_DIR / "emg_model.h"))
    args = parser.parse_args(argv)

    model = joblib.load(config.model_path(args.model))
    if not (hasattr(model, "coef_") and hasattr(model, "intercept_")):
        raise SystemExit("'{}' is not a linear model; export 'lda' or convert the model with emlearn / TFLite Micro.".format(args.model))
    W = np.atleast_2d(model.coef_)
    b = np.atleast_1d(model.intercept_)
    if W.shape != (len(config.GESTURES), len(config.FEATURE_NAMES)):
        raise SystemExit("unexpected coef_ shape {}".format(W.shape))

    normalizer = MinMaxNormalizer.load(config.artifact("normalizer_profile.json"))
    zc_threshold = float(np.load(config.artifact("step4_features.npz"))["zc_threshold"])
    sos = design_filters()

    # The C code computes argmax(W z + b); it must reproduce sklearn's predictions exactly.
    d = np.load(config.artifact("step6_dataset.npz"))
    manual = np.argmax(d["X_test"].astype(np.float32) @ W.T.astype(np.float32) + b.astype(np.float32), axis=1)
    agreement = float(np.mean(model.classes_[manual] == model.predict(d["X_test"])))
    print("float32 argmax(Wz+b) vs sklearn predict agreement on test set: {:.4%}".format(agreement))

    header = build_header(sos, normalizer, W, b, zc_threshold, args.model)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(header)
    flash = 4 * (sos.size + 2 * W.shape[1] + W.size + b.size)
    ram = 4 * config.N_CHANNELS * (config.WINDOW_SIZE + 2 * len(sos) + 1)
    print("Wrote {} (~{} B constants in flash, ~{} B pipeline state in RAM)".format(args.out, flash, ram))


if __name__ == "__main__":
    main()
